In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor


In [2]:
Target = pd.read_csv('target.csv')

In [3]:
Numerical = pd.read_csv('numerical.csv')

In [4]:
Categorical = pd.read_csv('categorical.csv')

In [5]:
Categorical.head()

STATE  CLUSTER HOMEOWNR GENDER  DATASRCE RFA_2R RFA_2A GEOCODE2 DOMAIN_A  \
0    IL       36        H      F         3      L      E        C        T   
1    CA       14        H      M         3      L      G        A        S   
2    NC       43        U      M         3      L      E        C        R   
3    CA       44        U      F         3      L      E        C        R   
4    FL       16        H      F         3      L      F        A        S   

   DOMAIN_B  ...  DOB_YR  DOB_MM  MINRDATE_YR  MINRDATE_MM  MAXRDATE_YR  \
0         2  ...      37      12           92            8           94   
1         1  ...      52       2           93           10           95   
2         2  ...       0       2           91           11           92   
3         2  ...      28       1           87           11           94   
4         2  ...      20       1           93           10           96   

   MAXRDATE_MM  LASTDATE_YR  LASTDATE_MM  FIRSTDATE_YR  FIRSTDATE_MM  
0            2           95           12            89            11  
1           12           95           12            93            10  
2            7           95           12            90             1  
3           11           95           12            87             2  
4            1           96            1            79             3  

[5 rows x 22 columns]

In [6]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(Categorical)
encoded_categorical = encoder.transform(Categorical).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical)

In [7]:
Target.shape

(95412, 2)

In [8]:
Target.head(10)

TARGET_B  TARGET_D
0         0       0.0
1         0       0.0
2         0       0.0
3         0       0.0
4         0       0.0
5         0       0.0
6         0       0.0
7         0       0.0
8         0       0.0
9         0       0.0

In [9]:
Numerical.shape

(95412, 315)

In [10]:
encoded_categorical.shape

(95412, 319)

In [11]:
df = pd.concat([Numerical, encoded_categorical, Target], axis=1)

In [12]:
df.shape

(95412, 636)

In [13]:
y=df['TARGET_B']
X=df.drop(columns=['TARGET_B'])

In [14]:
from sklearn.tree import DecisionTreeRegressor
model1 = DecisionTreeRegressor()
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()
from sklearn.neighbors import KNeighborsRegressor
model3 = KNeighborsRegressor()
from sklearn.preprocessing import StandardScaler
import numpy as np

scaler= StandardScaler()
X=scaler.fit_transform(X)

C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [20]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25)

In [16]:
from sklearn.model_selection import cross_val_score

model_pipeline = [model1, model2, model3]
model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']
model = DecisionTreeRegressor()


In [17]:
scores = cross_val_score(model, X, y, cv=5) 
scores

array([1., 1., 1., 1., 1.])

In [18]:
scores = {}
for model, model_name in zip(model_pipeline, model_names):
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_name] = mean_score
print(scores)


{'Decision Tree Regressor': 1.0, 'Linear Regression': -3.112257656051452e+22, 'KNN': -0.06693979338744474}


In [19]:
list(zip(model_pipeline, model_names))

[(DecisionTreeRegressor(), 'Decision Tree Regressor'),
 (LinearRegression(), 'Linear Regression'),
 (KNeighborsRegressor(), 'KNN')]

In [21]:
val_scores = {}

for model, model_name in zip(model_pipeline,model_names):
    model.fit(X_train, y_train)
    val_scores[model_name] = model.score(X_val,y_val)
print(val_scores)

{'Decision Tree Regressor': 1.0, 'Linear Regression': -4.405933005201527e+21, 'KNN': -0.05876020876933308}


In [22]:
transformer = StandardScaler().fit(X)
X = transformer.transform(X)

In [23]:
regr = DecisionTreeRegressor(max_depth=10,
                             criterion = 'squared_error',
                             min_samples_split=2,
                             min_samples_leaf = 1,
                             max_features = 6)


In [24]:
from sklearn.model_selection import cross_validate

results = cross_validate(regr,X_train, y_train, cv = 5)

In [25]:
print(results['test_score'])

[-0.03298558 -0.03476079 -0.04035541 -0.0211721   0.0689835 ]


In [26]:
print(results['test_score'].mean())

-0.01205807589889496


In [27]:
model_pipeline = [model1, model2, model3]
model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']

In [28]:
scores = {}
for model, model_name in zip(model_pipeline, model_names):
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_name] = mean_score
print(scores)

{'Decision Tree Regressor': 1.0, 'Linear Regression': -9.977817474504639e+22, 'KNN': -0.06763237429698248}


In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [33]:
y=df['TARGET_B']
X=df.drop(columns=['TARGET_B'])

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [37]:
X_train.shape


(76329, 635)

In [38]:
y_train.shape

(76329,)

In [36]:
trainset = pd.concat([X_train, y_train], axis=1)

In [41]:
category_0 = trainset[trainset['TARGET_B']==0].sample(len(trainset[trainset['TARGET_B']==1]))
print(category_0.shape)

(3843, 636)


In [42]:
category_1 = trainset[trainset['TARGET_B']== 1 ]

In [43]:
trainset_new = pd.concat([category_0, category_1], axis = 0)
trainset_new = trainset_new.sample(frac =1)

In [44]:
X_train = trainset_new.drop(['TARGET_B'], axis=1)
y_train = trainset_new['TARGET_B']
print(X_train.shape)

(7686, 635)


In [45]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)
y_train_regression = X_train['TARGET_D']
y_test_regression = X_test['TARGET_D']


In [46]:
X_train = X_train.drop(['TARGET_D'], axis = 1)
X_test = X_test.drop(['TARGET_D'], axis = 1)

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5, # max number of questions to ask.
                             min_samples_split=20, # amnount of rows still considered at every question
                             min_samples_leaf =20, # ultimate answer based on at least this many rows.
                             max_samples=0.8, #fraction of X-train to use in each tree
                             random_state = 42)



In [49]:
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))



C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.6424668227946917
0.5487082743803385


In [52]:
y_pred = clf.predict(X_test)
display(y_test.value_counts())


C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0    18083
1     1000
Name: TARGET_B, dtype: int64

In [51]:
display(confusion_matrix(y_test, y_pred))

array([[9867, 8216],
       [ 396,  604]], dtype=int64)

In [53]:
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(max_depth=5,
                             min_samples_split=20,
                             min_samples_leaf =20)
cross_val_scores = cross_val_score(clf, X_train, y_train, cv=10)
print(np.mean(cross_val_scores))

C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib

0.5845683653012571


C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [54]:
cross_val_scores

array([0.58777633, 0.58907672, 0.56957087, 0.57347204, 0.59297789,
       0.60208062, 0.59114583, 0.57552083, 0.58333333, 0.58072917])

In [55]:
cross_val_score(clf, X_train,y_train,cv=5, scoring='recall_macro')

C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\joanv\anaconda3\lib

array([0.5656697 , 0.57321891, 0.59077671, 0.56405691, 0.58292696])